# Generated by Django 5.2.4 on 2025-07-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
