# Generated by Django 5.2.4 on 2025-07-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_notes_user_alter_notes_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
